[build]
  publish = "."

[functions]
  directory = "netlify/functions"

[[headers]]
  for = "/public/*"
  [headers.values]
    Access-Control-Allow-Origin = "*"

[[headers]]
  for = "/.netlify/functions/*"
  [headers.values]
    Access-Control-Allow-Origin = "*"
    Access-Control-Allow-Headers = "*"
    Access-Control-Allow-Methods = "GET, POST, OPTIONS"


